# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Technical Communication and Rhetoric - Utah State University
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
author: >
  Technical Communication and Rhetoric at Utah State University
keywords: >
  arts, science, bachelor, undergraduate, technical communication

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

collections:
- sections

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "bachelors"
    values:
      section: "BA/BS in English: Professional and Technical Writing Emphasis"
      short: "Bachelor's Degree"
      menu: "Bachelor's"
  -
    scope:
      path: "masters"
    values:
      section: "Master of Technical Communication"
      short: "Master of Tech Comm"
      menu: "Master's"
  -
    scope:
      path: "phd"
    values:
      section: "Technical Communication and Rhetoric Doctoral Program"
      short: "TCR Doctoral Program"
      menu: "PhD"
  -
    scope:
      path: "people"
    values:
      section: "People"
      short: "People"
      menu: "People"
      
      
      
      
      
      